name: CI Workflow

permissions:
  contents: write
  id-token: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  test:
    name: Code quality checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install tox
        run: pip install tox
      - name: Run quality checks
        run: tox -e py39-lint,py39-type
      - name: Directory Cache
        uses: actions/cache@v4
        with:
          path: .tox
          key: tox-${{ runner.os }}-3.9-${{ hashFiles('tox.ini') }}
          restore-keys: |
            tox-${{ runner.os }}-3.9-

  build:
    name: Build and test docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: dockerfiles/base/*
      - name: Pull base image and build
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          python docker.py pull --build --push
      - name: Pull base image
        if: steps.changed-files.outputs.any_changed != 'true'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          python docker.py pull
